### ISSUE TITLE
exception: Cannot find null-safety text [Dart : 3.5.0-109.0.dev]

### ISSUE THREAD

**Issue by IndAlok** [worawit/blutter#78]
```
Dart version: 3.5.0-109.0.dev, Snapshot: 8787c610dd232d2d3efae139c322b964, Target: android arm64
flags: product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-tsan arm64 android compressed-pointers
exception: Cannot find null-safety text
```
https://www.mediafire.com/file/ugnwa4yf9nx9maa/arm64-Snapshot-8787c610dd232d2d3efae139c322b964.7z/file

**Comment by AbhiTheModder** [comment]
Most likely due to dev version, Dart devs implemented something new again...
a possible temporary fix
branch: `main-null-safety`
Modify the `DartLoader.cpp` like this: [#50](https://github.com/AbhiTheModder/blutter-termux/blob/main-null-safety/blutter/src/DartLoader.cpp#L50)

because there's no gurantee if dart devs will implement this onwards or will just use for some versions like #64

**Comment by yzctzl** [comment]
link to commit: https://github.com/dart-lang/sdk/commit/8e2acda7d68702d43eefae0c7b17d314d5c93b00#diff-0c27ee5540bcadf9531563ffd7dc5266b1475db16c6d75b73949611551452348
