### ISSUE TITLE
IDA decompiled code is incorrect

### ISSUE THREAD

**Issue by coderjingluo** [worawit/blutter#8]
![image](https://github.com/worawit/blutter/assets/35733451/a7ba1c6c-ce8e-4c33-bad8-1d9e04a4cbed)

When using IDA to decompile into c code, it seems that because it is written in dart, a function is decompiled to incorrect code in many places。Do you have a way to get ida to decompile the correct c code from the dart stack?
https://www.guardsquare.com/blog/obstacles-in-dart-decompilation-and-the-impact-on-flutter-app-security

**Comment by worawit** [comment]
IDA cannot decompile correctly because Dart use its own call convention, register usages, ...
In the link, they patch Stack pointer, manually set call arguments for functions, manually create struct for Dart objects to get the nice result. But you have to understand Dart call convention and objects to do it.

In my opinion, reading the assembly with comment is easier than wrong decompiled code.

Note: The code analysis feature is still developing. When finished, more information will be shown in the assembly. Then code should be easier to read.
